### ISSUE TITLE
Ethernet on ATMEGA4809 still not working

### ISSUE THREAD

**Issue by Werner-Losken** [MCUdude/MegaCoreX#207]
Dear Forum,
I am trying to get ethernet working on a ATMEGA4809 40 pin, a W5500 module is attached to the SPI interface (See attachments)
If I compile code for Nano Every, which also has ATMEGA4809 processor it just passes without errors.
But if I compile code for ATMEGA4809 the compiler stops with error:
c:\Users\WinAVR\Documents\Arduino_2.01\libraries\Ethernet\src\Dns.cpp:99:20: error: 'INADDR_NONE' was not declared in this scope 

For code and and errorlog see attachments.

I hope you can help me with this,
Werner

[Errorlog_4809_ethernet.txt](https://github.com/user-attachments/files/19774779/Errorlog_4809_ethernet.txt)
[Testcode_4809_ethernet.txt](https://github.com/user-attachments/files/19774777/Testcode_4809_ethernet.txt)
[ATMEGA4809_W5500_SD.pdf](https://github.com/user-attachments/files/19774778/ATMEGA4809_W5500_SD.pdf)

**Comment by MCUdude** [comment]
v1.1.4 is now available though boards manager, which should have this issue resolved.

**Comment by Werner-Losken** [comment]
Dear Hans,

 

Thank you so much for your email. I was so happy to see it, I thought my problem is solved!

 

I have updated to 1.1.4, but unfortunately the problem is still the same. I also did a reinstall of ethernet and MegaCoreX.

(c:\Users\WinAVR\Documents\Arduino_2.01\libraries\Ethernet\src\Dns.cpp:99:20: error: 'INADDR_NONE' was not declared in this scope)   

Could you please have a look at it otherwise I have to redesign a complete PCB (Big one ☹) and use other processor.

 

Attached the errorlog and code snippet.

 

Thank you very much in advance,

 

Werner

 

 

Met vriendelijke groeten,

 

Ing. Werner F.P.Lösken

 

Eendrachtstraat 12

B-3920 Lommel

Belgium

Gsm:  +32 (0) 498 84 00 78

Email: ***@***.*** ***@***.***> 

P Please consider the environment before printing this e-mail

**Comment by MCUdude** [comment]
Can you try to downgrade to MegaCoreX v1.1.2? This uses an older version of the Ethernet library, which may not have the issue you're facing.

**Comment by MCUdude** [comment]
Sorry to bother you again @DrItanium, but the fix you provided for the ethernet library is still causing problems.

The example @Werner-Losken provided is nice and small.

```
#include <SPI.h>
#include <Ethernet.h>


byte mac[] = { 0xA8, 0x61, 0x0A, 0xAE, 0x79, 0xF9 };
IPAddress ip(192,168,1,170);

void setup()
{
SPI.begin();
Serial.begin(57600,SERIAL_8N1);
}

void loop()
{
  Serial.println("Starting w5500");
  Ethernet.begin(mac,ip);
  Serial.println(Ethernet.localIP());
  while(1){}
}
```

This example compiles when using MegaCoreX v1.1.2 (pre #198 and #202), but not compile with the latest v1.1.4, which includes PR #202). Do you have time to look into this again? If you're able to figure it out, I'm ready to release v1.1.5 with the fix as soon as possible.

**Comment by DrItanium** [comment]
I am currently not near my computer. I'll take a look at this later today.

**Comment by DrItanium** [comment]
Okay, I had some downtime in between tasks. This problem stems from the
fact that I grafted code in from a much newer Arduino API version.

The fix is very simple and I will have a new pull request up later tonight.

**Comment by DrItanium** [comment]
Pull request up

**Comment by Werner-Losken** [comment]
Dear All,Thanks very much!The code is compiling, now I can test my hardware😀Kind regardsWernerMet vriendelijke groeten,Werner LöskenIng. Werner F.P. LöskenEendrachtstraat 123920 LommelBelgiumE-mail: ***@***.***: +32 498 840078Sent from my iPhoneOn 15 May 2025, at 18:03, Hans ***@***.***> wrote:﻿
Closed #207 as completed via #208.

**Comment by MCUdude** [comment]
MegaCoreX v1.1.5 is now available through Boards Manager. Thank you for your help @DrItanium!
